# On every push this script is executed
on: 
 push:
  branches:
   - main
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install-zola
        run: |
          curl -sSL https://github.com/getzola/zola/releases/download/v0.15.3/zola-v0.15.3-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C /usr/local/bin
          chmod +x /usr/local/bin/zola
      - name: build
        run: |
          export BASE_URL="https://hugyouu.github.io/hugo-pierret"
          zola build
      - name: deploy
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          #TOKEN: ${{ secrets.TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
